# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Unibo.Alchemist
PackageVersion: 30.0.5
PackageLocale: en-US
Publisher: Unibo
PackageName: Alchemist
License: GPLv3
ShortDescription: an extensible simulator for pervasive computing
ManifestType: defaultLocale
ManifestVersion: 1.5.0
